name: Terraform Lint

on:
  push:
    branches: [ main, develop ]
    paths:
      - '**.tf'
      - '**.tfvars'
      - '.github/workflows/terraform-validate.yml'
  pull_request:
    paths:
      - '**.tf'
      - '**.tfvars'
      - '.github/workflows/terraform-validate.yml'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Format Check
      id: fmt
      run: |
        cd game-servers-vultr
        terraform fmt -check -recursive
      continue-on-error: true

    - name: Format Check Results
      if: steps.fmt.outcome == 'failure'
      run: |
        echo "❌ Terraform files need formatting!"
        echo "Run the following command to fix formatting:"
        echo "  cd game-servers-vultr && terraform fmt -recursive"
        exit 1

    - name: Init
      run: |
        cd game-servers-vultr
        terraform init -backend=false

    - name: Validate
      run: |
        cd game-servers-vultr
        terraform validate
